cc_library(
    name = "crypto",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//include/crypto:crypto_headers",
        "@openssl//:openssl",
        ],
)
