cc_library(
    name ="network",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//include/network:network_headers",
        "//src/protocol:protocol",
        "//src/core:core",
        "@boost.asio//:boost.asio"
        ],
)
